spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Jimu131207!
    url: jdbc:mysql://101.126.23.137:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  flyway:
    baseline-on-migrate: true  # initialize existing schema without history table
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 101.126.23.137
    database: 0
    port: 6379
    password: MyRedis2025!
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
